<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>PEG.js with LiveScript</string>
	<key>fileTypes</key>
	<array>
		<string>pegls</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>PEG.js LiveScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#commentBlock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#commentLine</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#docCommentLine</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literalDouble</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literalSingle</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#charSet</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#exprLabel</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rule</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ruleRef</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#scriptblock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pegOperator</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>charSet</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>string.pegls</string>
		</dict>
		<key>commentBlock</key>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.pegls</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.block.pegls</string>
		</dict>
		<key>commentLine</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.pegls</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.pegls</string>
		</dict>
		<key>docCommentBlock</key>
		<dict>
			<key>begin</key>
			<string>/\*\*(?!/)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.pegls</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.pegls</string>
		</dict>
		<key>exprLabel</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z$_][a-zA-Z$_0-9]*:</string>
			<key>name</key>
			<string>variable.parameter.pegls</string>
		</dict>
		<key>literalDouble</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.pegls</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.pegls</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.pegls</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.pegls</string>
				</dict>
			</array>
		</dict>
		<key>literalSingle</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.pegls</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.pegls</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.pegls</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.pegls</string>
				</dict>
			</array>
		</dict>
		<key>pegOperator</key>
		<dict>
			<key>match</key>
			<string>[+*?&amp;!$=/]</string>
			<key>name</key>
			<string>keyword.operator.pegls</string>
		</dict>
		<key>rule</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.pegls</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.pegls</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([a-zA-Z$_][a-zA-Z$_0-9]*)[ \t]*("[^"]*"|'[^']*')?[ \t]*=?</string>
		</dict>
		<key>ruleRef</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z$_][a-zA-Z$_0-9]*</string>
			<key>name</key>
			<string>entity.name.type.pegls</string>
		</dict>
		<key>scriptblock</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>source.livescript.embedded.pegls</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#scriptblock</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.livescript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ls</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.pegls</string>
	<key>uuid</key>
	<string>a0686268-66df-4e3f-bdc7-a9140fee2a33</string>
</dict>
</plist>
